version: '3.8'

services:
  frontend:
    build:
      context: ./task-manager-app
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./task-manager-backend
    ports:
      - "3000:3000"
